name: Generate ASCII Artwork

on:  
  push

jobs:
  asccii_job:
    runs-on: ubuntu-latest
    steps:
        - name: checkout Repo 
          uses: actions/checkout@v4
   
        - name: list repo  files
          run: ls -ltra
        
        - name: Execution of shell Script
          run: |
            chmod 777 ascii-script.sh
            ./ascii-script.sh
