name: Exploring varaibles and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: s009
    IMAGE_NAME: github-action-nginx


jobs:
    docker:
        runs-on: ubunut-latest
        steps:
        - name: Docker build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker-run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME