name: Exploring varaibles and secrets

on:
    workflow_dispatch: 



env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: s009
    IMAGE_NAME: github-action-nginx


jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

    deploy:
        timeout-minutes: 1
        needs: docker
        concurrency: 
            group: production-devlopment
            cancel-in-progress: true 
        runs-on: ubuntu-latest
        steps:
        - name: Docker-run
          timeout-minutes: 1 
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME